### ISSUE TITLE
Errors when installed on clean El Capitan 10.11

### ISSUE THREAD

**Issue by webfed** [BrianGilbert/OSXAegirInstaller#49]
Things go wrong when installing composer. Do you need more info?

https://gist.github.com/webfed/f0de69193619ffaac037#file-aegir-install-logfile-2015-10-log

**Comment by BrianGilbert** [comment]
It looks like the issue was caused because you have php56 installed..?

**Comment by webfed** [comment]
Yes, like the previous issue. That must be standard with 10.11 since the only thing I installed after the OS is Xcode. Maybe add uninstall to the script? I can test it on a clean install.
First I will reinstall 10.11 and see what is installed.

**Comment by BrianGilbert** [comment]
it's erroring on 'php56' (which means it was installed via homebrew not just present in OS X)..

you can rerun the script to uninstall.

**Comment by webfed** [comment]
And after that rerun the script to install Aegir you mean?

**Comment by BrianGilbert** [comment]
yep, run once to install, run again to uninstall..

**Comment by webfed** [comment]
But then php56 will be installed again, it happened during install of Aegir. Shouldn't there be made a change in the script to prevent this happening?

**Comment by BrianGilbert** [comment]
Impossible for it to install php56, unless something in homebrew has added it as a dependancy (Looks like it may be a dependancy of composer installed via homebrew) .. if thats the case it may not be fixable very quickly.

**Comment by webfed** [comment]
That must be it.
However it says version required is 5.3.2
https://getcomposer.org/doc/00-intro.md
Strange

**Comment by BrianGilbert** [comment]
I looks like it php56 should only get installed if no other version is linked..  https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb

**Comment by webfed** [comment]
So I should have the installer install at least 2 versions op php?

**Comment by BrianGilbert** [comment]
I think I see the issue..  give me a tic

**Comment by webfed** [comment]
I am not a native english speaker, what does give me a tic mean :-)

**Comment by BrianGilbert** [comment]
You'll need to uninstall, then re-download the script before installing again..

I think it was possibly because drush master branch is for Drupal 8 now.. updated it to install 7.x

**Comment by webfed** [comment]
Thanks! Will try and report

**Comment by webfed** [comment]
Installing only one version of php fails, so uninstalled and reinstalled.
It stopped at mysql configuration, I had to enter this to continue in another terminal window:
aegir:~ gerard$ touch /tmp/mysql.sock
aegir:~ gerard$ mysql.server start
Starting MySQL
. SUCCESS! 

After that when starting with provision drush could not be found.

https://gist.github.com/webfed/04db005bc3332e7e68e7#file-aegir-install-logfile-2015-10-06-07-51-16-log

**Comment by BrianGilbert** [comment]
Issue created for root cause of install fail:
https://github.com/Homebrew/homebrew-php/issues/2437

**Comment by BrianGilbert** [comment]
Confirmed as an issue with home-brew-php repo.

**Comment by michaeljs1990** [comment]
I posted how to fix this in the issue you opened if you want to move forward and not wait for upstream to fix it @webfed

**Comment by webfed** [comment]
@michaeljs1990 thanks, much appreciated

**Comment by BrianGilbert** [comment]
@webfed The issue is now fixed upstream
