### ISSUE TITLE
Install on El Capitan nginx does not start

### ISSUE THREAD

**Issue by webfed** [BrianGilbert/OSXAegirInstaller#50]
On a clean install of OS.
One error, mysql is not started so I had to: mysql.server start
Everything seems to go well except for nginx.

https://gist.github.com/webfed/4d1ae395ea978a402168#file-aegir-install-logfile-2015-10-14-18-38-36-log

**Comment by BrianGilbert** [comment]
@webfed we resolved this by finding the upstream issue didn't we?

**Comment by BrianGilbert** [comment]
mysql not starting fixed just now, and confirmed with this fix that nginx loads

**Comment by webfed** [comment]
Thanks for your time. I tried again on a clean install of 10.11.1

I am afraid there still is a problem with nginx.

When I try to start it:
https://gist.github.com/webfed/d0383584f4142ab32470


Also hostmaster-7.x.3.1 was installed while I answered no when asked to install this version.

This is the log
https://gist.github.com/webfed/2166acc26d17cdb85226

**Comment by BrianGilbert** [comment]
@webfed 

Ah I had a symlink creation in the wrong place..

you should be able to just run the following to get it up (you can ignore the pid error if you see it, it will only ocurr once):
```
sudo mkdir -p /var/log/nginx
ln -s /var/log/nginx/access.log /var/log/aegir/nginx-access.log
sudo nginx -s stop;sudo nginx

**Comment by BrianGilbert** [comment]
oh, also.. Aegir 7.x-3.1 is what gets installed if you don't select aegir dev as this is now the stable version.
