### ISSUE TITLE
adding php70 support?

### ISSUE THREAD

**Issue by infinityartworx** [BrianGilbert/OSXAegirInstaller#51]
Can we add php70 so we can go70 ? That would be awesome

**Comment by BrianGilbert** [comment]
@infinityartworx I could add php7 as an option but Aegir won't work with it so no point in allowing it to be set as a default, I asked for confirmation from the aegir team and the answer was "It almost certainly does not at this point in time.".

**Comment by infinityartworx** [comment]
Hi @BrianGilbert, thank you for replying very fast! As we are developing mostly of our times in Drupal 7 php 7.0 is not supported fully... but it is superfast. So i've added php7.0 manually to the go scripts and it works. But i understand that it can't be added by a very good reason. Again thank you Brian!
