### ISSUE TITLE
Hostmaster install fails when upgrading

### ISSUE THREAD

**Issue by joachimroeleveld** [BrianGilbert/OSXAegirInstaller#52]
Hi Brian, 

I'm trying to upgrade after I installed El Capitan.

The installation process finished successfully, but the hostmaster install terminated with the following:

```
Configuring default blocks                                           [1;32;40m[1m[status][0m
Generated config in write(): Drupal sites.php file                   [1;32;40m[1m[success][0m
(/var/aegir/hostmaster-7.x-3.x/sites/sites.php)
Changed permissions of /var/aegir/hostmaster-7.x-3.x/sites/sites.php [1;32;40m[1m[success][0m
to 644
Could not find the alias @hostmaster                                 [31;40m[1m[error][0m
Illegal string offset 'site' backend.inc:1030                        [1;33;40m[1m[warning][0m
The command could not be executed successfully (returned: Could not  [31;40m[1m[error][0m
find the alias @hostmaster                                
[31;40m[1m[error][0m
, code: 1)
```

Indeed, executing `drush sa` shows only the following:

```
@platform_drupal734
@platform_hostmaster
@server_localhost
@server_master 
```

You have any idea what could've gone wrong?

**Comment by joachimroeleveld** [comment]
In the meantime I installed [Aegir with Docker](https://github.com/DominicBoettger/docker-aegir-mariadb). In combination with Unison (syncs files into the container and back) I now have quite an efficient development environment. Got it working pretty fast and it's completely isolated from my operating system. In my opinion it's a better option than to clutter your Mac with a bunch of dependencies and config files. I used OSXAegirInstaller a long time though, thanks for your efforts in maintaining it!

**Comment by BrianGilbert** [comment]
I'd love to hear more about how you hooked up unison for that..

**Comment by joachimroeleveld** [comment]
I used [this](https://github.com/leighmcculloch/docker-unison) to start a Unison container. The Aegir container mounts `/mnt/sda1/var/aegir` (persistent) on `/var/aegir` and the Unison container mounts `/mnt/sda1/var/aegir/platforms` on `/unison`. Then, on my mac, my project folder contains only the site's `themes`, `modules`, `libraries` and `files` filders, which I monitor with fswatch for changes (see Unison container repo for an example). If I make any change locally, fswatch notifies Unison which on its turn syncs the changed files.

**Comment by joachimroeleveld** [comment]
This is my `docker-compose.yml`:

	aegir:
	  image: aegir
	  container_name: aegir
	  ports:
	    - "80:80"
	    - "23:22"
	  volumes:
	    - /mnt/sda1/var/aegir/var/aegir:/var/aegir
	    - /mnt/sda1/var/aegir/var/log/apache2:/var/log/apache2
	    - /mnt/sda1/var/aegir/var/lib/mysql:/var/lib/mysql
	    - /mnt/sda1/var/aegir/etc/mysql/conf.d:/etc/mysql/conf.d
	    - /mnt/sda1/var/aegir/etc/mysql/sites-enabled:/etc/mysql/sites-enabled
	  environment:
	    - POSTFIX_RELAY_HOST=smtp.gmail.com
	    - POSTFIX_RELAY_PORT=587
	    - POSTFIX_MAILNAME=aegir.ld
	    - POSTFIX_DESTINATION=info@example.com
	    - POSTFIX_USER=info@example.com
	    - POSTFIX_PASSWD=password_here
	    - AEGIR_SITE=aegir
	    - AEGIR_FRONTEND_URL=aegir.ld
	    - AEGIR_EMAIL=info@example.com
	    - AEGIR_DB_PASSWORD=aegir
	    - AEGIR_VERSION=7.x-3.2
	    - MYSQL_ROOT_PW=root
	  hostname: aegir
	unison:
	  image: leighmcculloch/unison
	  environment:
	    - UNISON_VERSION=2.40.102
	  ports:
	    - "5000:5000"
	  volumes:
	    - /mnt/sda1/var/aegir/var/aegir/platforms:/unison
